{"uuid": "f6f972f8-422e-4804-8137-edde4d70416e", "children": ["c7163635-70f0-4ee8-bd75-93f3abf330e4", "267363fd-4a75-4f71-86bb-e9eb9bac2b97", "f2414cb9-ef96-4072-bda5-d7b566687cda"], "befores": [{"name": "xunit_setup_module_fixture_test_gzAndroidAuto", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error getting device platform version. Original error: Error executing adbExec. Original error: 'Command 'C:\\\\Users\\\\Hello\\\\AppData\\\\Local\\\\Android\\\\Sdk\\\\platform-tools\\\\adb.exe -P 5037 -s R58N828LKMP shell getprop ro.build.version.release' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability\n\n", "trace": "  File \"C:\\Users\\Hello\\PycharmProjects\\gz_ui_auto\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Hello\\PycharmProjects\\gz_ui_auto\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Hello\\PycharmProjects\\gz_ui_auto\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\Hello\\PycharmProjects\\gz_ui_auto\\venv\\Lib\\site-packages\\_pytest\\python.py\", line 533, in xunit_setup_module_fixture\n    _call_with_optional_argument(setup_module, request.module)\n  File \"C:\\Users\\Hello\\PycharmProjects\\gz_ui_auto\\venv\\Lib\\site-packages\\_pytest\\python.py\", line 741, in _call_with_optional_argument\n    func()\n  File \"C:\\Users\\Hello\\PycharmProjects\\gz_ui_auto\\test_gzAndroidAuto.py\", line 17, in setup_module\n    driver = StartAppium.start_appium()\n  File \"C:\\Users\\Hello\\PycharmProjects\\gz_ui_auto\\gz_start_appium.py\", line 20, in start_appium\n    driver = webdriver.Remote(gz_public.gzAppiumH, desired_caps, direct_connection=True)\n  File \"C:\\Users\\Hello\\PycharmProjects\\gz_ui_auto\\venv\\Lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 267, in __init__\n    super().__init__(\n  File \"C:\\Users\\Hello\\PycharmProjects\\gz_ui_auto\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"C:\\Users\\Hello\\PycharmProjects\\gz_ui_auto\\venv\\Lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 357, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\n  File \"C:\\Users\\Hello\\PycharmProjects\\gz_ui_auto\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Hello\\PycharmProjects\\gz_ui_auto\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1644051019889, "stop": 1644051041795}], "start": 1644051019889, "stop": 1644051042145}