{"uuid": "c59f5755-483d-4344-b46f-bff64b77e42f", "children": ["377ed982-058f-4bf8-83f5-b720e7ca567e"], "befores": [{"name": "xunit_setup_method_fixture_TestAddDevices", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.glazero.android' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Error executing adbExec. Original error: 'Command 'C:\\\\Users\\\\Hello\\\\AppData\\\\Local\\\\Android\\\\Sdk\\\\platform-tools\\\\adb.exe -P 5037 -s R58N828LKMP shell am start -W -n com.glazero.android/com.glazero.android.SplashActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' exited with code 1'; Command output: adb.exe: device unauthorized.\r\nThis adb server's $ADB_VENDOR_KEYS is not set\r\nTry 'adb kill-server' if that seems wrong.\r\nOtherwise check for a confirmation dialog on your device.\r\n\n\n", "trace": "  File \"C:\\Users\\Hello\\PycharmProjects\\gz_ui_auto\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Hello\\PycharmProjects\\gz_ui_auto\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Hello\\PycharmProjects\\gz_ui_auto\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\Hello\\PycharmProjects\\gz_ui_auto\\venv\\Lib\\site-packages\\_pytest\\python.py\", line 841, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"C:\\Users\\Hello\\PycharmProjects\\gz_ui_auto\\venv\\Lib\\site-packages\\_pytest\\python.py\", line 739, in _call_with_optional_argument\n    func(arg)\n  File \"C:\\Users\\Hello\\PycharmProjects\\gz_ui_auto\\test_gzAndroidAuto.py\", line 276, in setup_method\n    master.launch_app()\n  File \"C:\\Users\\Hello\\PycharmProjects\\gz_ui_auto\\venv\\Lib\\site-packages\\appium\\webdriver\\extensions\\applications.py\", line 115, in launch_app\n    self.execute(Command.LAUNCH_APP)\n  File \"C:\\Users\\Hello\\PycharmProjects\\gz_ui_auto\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Hello\\PycharmProjects\\gz_ui_auto\\venv\\Lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 31, in check_response\n    raise wde\n  File \"C:\\Users\\Hello\\PycharmProjects\\gz_ui_auto\\venv\\Lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 26, in check_response\n    super().check_response(response)\n  File \"C:\\Users\\Hello\\PycharmProjects\\gz_ui_auto\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1659467359474, "stop": 1659467361163}], "start": 1659467359474, "stop": 1659467361492}